Models/Exam.cs
using System.ComponentModel.DataAnnotations;

namespace OnlineExam.Models
{
    public class Exam
    {
        [Key]
        public int ExamId { get; set; }

        [Required(ErrorMessage = "Title is required.")]
        [StringLength(200, ErrorMessage = "Title cannot be longer than 200 characters.")]
        [RegularExpression(@"^[a-zA-Z\s]+$", ErrorMessage = "Full name must only contain letters and spaces.")]
        public string Title { get; set; } = null!;

        [StringLength(500, ErrorMessage = "Description cannot be longer than 500 characters.")]
        [Required(ErrorMessage = "Description is required.")]
        public string? Description { get; set; }

        [Required(ErrorMessage = "Start time is required.")]
        [DataType(DataType.DateTime, ErrorMessage = "Invalid date format.")]
        public DateTime StartTime { get; set; }

        [Required(ErrorMessage = "End time is required.")]
        [DataType(DataType.DateTime, ErrorMessage = "Invalid date format.")]
        public DateTime EndTime { get; set; }

        [StringLength(100, ErrorMessage = "Created by cannot be longer than 100 characters.")]
        [RegularExpression(@"^[a-zA-Z\s]+$", ErrorMessage = "Full name must only contain letters and spaces.")]
        [Required(ErrorMessage = "CreatedBy is required.")]
        public string? CreatedBy { get; set; }

        public virtual ICollection<Question>? Questions { get; set; } = new HashSet<Question>();

        public virtual ICollection<Result> Results { get; set; } = new List<Result>();

    }
}

Controllers/ExamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineExam.Data;
using OnlineExam.Models;

namespace OnlineExam.Controllers
{
    public class ExamsController : Controller
    {
        private readonly OnlineExamContext _context;

        public ExamsController(OnlineExamContext context)
        {
            _context = context;
        }

        // GET: Exams
        public async Task<IActionResult> Index()
        {
            

            var availableExams = await _context.Exams

                .ToListAsync();
            ViewBag.msg = "Admin";

            return View(availableExams);
        }

        // GET: Exams/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var exam = await _context.Exams
                .FirstOrDefaultAsync(m => m.ExamId == id);
            if (exam == null)
            {
                return NotFound();
            }

            return View(exam);
        }

        // GET: Exams/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Exams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ExamId,Title,Description,StartTime,EndTime,CreatedBy")] Exam exam)
        {
            if (ModelState.IsValid)
            {
                _context.Add(exam);
                await _context.SaveChangesAsync();
                
                return RedirectToAction(nameof(Index));
            }
            return View(exam);
        }

        // GET: Exams/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var exam = await _context.Exams.FindAsync(id);
            if (exam == null)
            {
                return NotFound();
            }
            return View(exam);
        }

        // POST: Exams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ExamId,Title,Description,StartTime,EndTime,CreatedBy")] Exam exam)
        {
            if (id != exam.ExamId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(exam);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ExamExists(exam.ExamId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(exam);
        }

        // GET: Exams/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var exam = await _context.Exams
                .FirstOrDefaultAsync(m => m.ExamId == id);
            if (exam == null)
            {
                return NotFound();
            }

            return View(exam);
        }

        // POST: Exams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var exam = await _context.Exams.FindAsync(id);
            if (exam != null)
            {
                _context.Exams.Remove(exam);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ExamExists(int id)
        {
            return _context.Exams.Any(e => e.ExamId == id);
        }
        public async Task<IActionResult> AddQuestions(int id)
        {
            var exam = await _context.Exams.FindAsync(id);
            if (exam == null)
            {
                return NotFound();
            }

            return View(new Question
            {
                ExamId = id
            });
        }

        // POST: Exam/AddQuestions
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddQuestions(Question question)
        {
            if (ModelState.IsValid)
            {
                _context.Questions.Add(question);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", new { id = question.ExamId });
            }

            return View(question);
        }

        // GET: Exam/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var exam = await _context.Exams
                .Include(e => e.Questions)
                .FirstOrDefaultAsync(e => e.ExamId == id);

            if (exam == null)
            {
                return NotFound();
            }

            return View(exam);


        }

        public async Task<IActionResult> StudentExams()
        {
            // Assuming that student's ID is stored in session after login
            var studentId = HttpContext.Session.GetInt32("StudentId");

            if (studentId == null)
            {
                // Redirect to login page if student ID is not available
                return RedirectToAction("Login", "Students");
            }

            var exams = await _context.Exams
                .Where(e => !e.Results.Any(r => r.StudentId == studentId))
                .ToListAsync();

            return View(exams);
        }

        // GET: Exams/StartExam/5
        public async Task<IActionResult> StartExam(int id)
        {
            var exam = await _context.Exams
                .Include(e => e.Questions)
                .FirstOrDefaultAsync(e => e.ExamId == id);

            if (exam == null)
            {
                return NotFound();
            }

            return View(exam);
        }
        [HttpPost]
        public IActionResult SubmitExam(int examId)
        {
            // Check if the student is logged in
            var studentId = HttpContext.Session.GetInt32("StudentId");
            if (studentId == null)
            {
                return RedirectToAction("Login", "Students");
            }

            // Use TempData to pass a success message to the view
            TempData["SuccessMessage"] = "Exam submitted successfully!";

            // Redirect back to the exam page or wherever appropriate
            return RedirectToAction("StartExam", new { id = examId });

        }

    }

}

Views/Exams/AddQuestions.cshtml
@model OnlineExam.Models.Question

@{
    ViewData["Title"] = "AddQuestions";
}

<h1>AddQuestions</h1>

<h4>Question</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddQuestions">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ExamId" class="control-label"></label>
                <select asp-for="ExamId" class ="form-control" asp-items="ViewBag.ExamId"></select>
            </div>
            <div class="form-group">
                <label asp-for="QuestionText" class="control-label"></label>
                <input asp-for="QuestionText" class="form-control" />
                <span asp-validation-for="QuestionText" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OptionA" class="control-label"></label>
                <input asp-for="OptionA" class="form-control" />
                <span asp-validation-for="OptionA" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OptionB" class="control-label"></label>
                <input asp-for="OptionB" class="form-control" />
                <span asp-validation-for="OptionB" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OptionC" class="control-label"></label>
                <input asp-for="OptionC" class="form-control" />
                <span asp-validation-for="OptionC" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OptionD" class="control-label"></label>
                <input asp-for="OptionD" class="form-control" />
                <span asp-validation-for="OptionD" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CorrectOption" class="control-label"></label>
                <input asp-for="CorrectOption" class="form-control" />
                <span asp-validation-for="CorrectOption" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Exams/Create.cshtml
@model OnlineExam.Models.Exam

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Exam</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartTime" class="control-label"></label>
                <input asp-for="StartTime" class="form-control" />
                <span asp-validation-for="StartTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndTime" class="control-label"></label>
                <input asp-for="EndTime" class="form-control" />
                <span asp-validation-for="EndTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedBy" class="control-label"></label>
                <input asp-for="CreatedBy" class="form-control" />
                <span asp-validation-for="CreatedBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Exams/Delete.cshtml
@model OnlineExam.Models.Exam

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Exam</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ExamId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Exams/Details.cshtml
@model OnlineExam.Models.Exam

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Exam</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ExamId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Exams/Edit.cshtml
@model OnlineExam.Models.Exam

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Exam</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ExamId" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartTime" class="control-label"></label>
                <input asp-for="StartTime" class="form-control" />
                <span asp-validation-for="StartTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndTime" class="control-label"></label>
                <input asp-for="EndTime" class="form-control" />
                <span asp-validation-for="EndTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedBy" class="control-label"></label>
                <input asp-for="CreatedBy" class="form-control" />
                <span asp-validation-for="CreatedBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Exams/Index.cshtml
@model IEnumerable<OnlineExam.Models.Exam>

@{
    ViewData["Title"] = "Available Exams";
    var userRole = Context.Session.GetString("Role");
}

<h1>Available Exams</h1>

@if (Model.Any())
{
    <ul class="list-group">
        @foreach (var exam in Model)
        {
            <li class="list-group-item">
                <h5>@exam.Title</h5>
                <p>@exam.Description</p>

                @switch (userRole)
                {
                    case "Admin":
                       
                        break;

                    case "Student":
                        <a href="@Url.Action("StartExam", "Exams", new { id = exam.ExamId })" class="btn btn-primary">Start Exam</a>
                        break;

                    default:
                        <a asp-action="Edit" asp-route-id="@exam.ExamId" class="btn btn-secondary">Edit</a>
                        <a asp-action="Details" asp-route-id="@exam.ExamId" class="btn btn-info">Details</a>
                        <a asp-action="Delete" asp-route-id="@exam.ExamId" class="btn btn-danger">Delete</a>
                        
                        break;
                }
            </li>
        }
    </ul>
}
else
{
    <p>No exams are currently available.</p>
}

Views/Exams/StartExam.cshtml
@model OnlineExam.Models.Exam

@{
    ViewData["Title"] = "Start Exam";
}

<h1>@Model.Title</h1>

<p>@Model.Description</p>
<br />
@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success">
        @TempData["SuccessMessage"]
    </div>
}

<form asp-action="SubmitExam" method="post">
    @foreach (var question in Model.Questions)
    {
        <div class="form-group">
            <label>@question.QuestionText</label>
            <div class="form-check">
                <input type="radio" name="answers[@question.QuestionId]" value="A" class="form-check-input" id="question_@question.OptionA">
                <label class="form-check-label" for="question_@question.OptionA">
                    @question.OptionA
                </label>
            </div>
            <div class="form-check">
                <input type="radio" name="answers[@question.QuestionId]" value="B" class="form-check-input" id="question_@question.OptionB">
                <label class="form-check-label" for="question_@question.OptionB">
                    @question.OptionB
                </label>
            </div>
            <div class="form-check">
                <input type="radio" name="answers[@question.QuestionId]" value="C" class="form-check-input" id="question_@question.OptionC">
                <label class="form-check-label" for="question_@question.OptionC">
                    @question.OptionC
                </label>
            </div>
            <div class="form-check">
                <input type="radio" name="answers[@question.QuestionId]" value="D" class="form-check-input" id="question_@question.OptionD">
                <label class="form-check-label" for="question_@question.OptionD">
                    @question.OptionD
                </label>
            </div>
        </div>
    }
    <input type="hidden" name="examId" value="@Model.ExamId" />
    <button type="submit" class="btn btn-primary">Submit Exam</button>
</form>
<br />
<div>
    <a asp-action="Index">Back to</a>
</div>